# 配置端口
server.port= 8090

mybatis.configuration.log-impl= org.apache.ibatis.logging.stdout.StdOutImpl

face.enabled=false
face.appId=4Wy2aFP5JJDQQua3WqxvxsWJnMBDh2qQnf8dJfonSgsE
face.sdkKey=J9uvaT8zDnTj1whsGrC7LVhsM4or78VKtKNCAqF9Hg3B
face.activeKey=86M1-11Z6-L13Q-D8GK
face.libPath=/source/server/libs/WIN64


# 串口配置
serial.enabled=false
serial.serialPort=COM3

# 阻燃粉比例区间（分母），实际加料重量/阻燃粉重量 应在 [ratioMin, ratioMax] 范围内
app.pickingBottomThreshold=5
app.flameRetardantRatioMin=25
app.flameRetardantRatioMax=35