# 配置端口
server.port= 80

spring.datasource.url= jdbc:sqlite:data/db/tee.db
spring.datasource.driver-class-name= org.sqlite.JDBC
# 初始化表
spring.datasource.schema= classpath:db/table.sql
# 初始化数据
spring.datasource.data= classpath:db/data.sql
spring.datasource.initialization-mode= always
spring.datasource.continue-on-error= true

#人脸识别sdk相关 从官网获取
face.libPath=/libs/WIN64

#人脸相似度阈值
face.enabled=true
face.score=0.85
face.path=data/face/
face.path.back=data/face/back/

# 上传最大文件限制
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

log.path=data/log

# 串口配置
serial.enabled=true
serial.serialPort=COM1
