# 配置端口
server.port= 8090
#spring.profiles.active=pro
# 配置数据源
#spring.datasource.jdbc-url= jdbc:mysql://localhost:3306/tee?useSSL=false&serverTimezone=UTC
#spring.datasource.username= root
#spring.datasource.password= nsFz2020
#spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver

spring.datasource.username=
spring.datasource.password=
spring.datasource.url= jdbc:sqlite:data/db/tee.db
spring.datasource.driver-class-name= org.sqlite.JDBC
# 初始化表
spring.datasource.schema= classpath:db/table.sql
# 初始化数据
spring.datasource.data= classpath:db/data.sql
spring.datasource.initialization-mode= always
spring.datasource.continue-on-error= true

# mybatis配置
mybatis.mapper-locations= classpath:com/tee/mapper/*.xml
mybatis.type-aliases-package= com.tee.pojo.vo
mybatis.configuration.log-impl= org.apache.ibatis.logging.stdout.StdOutImpl

#人脸识别sdk相关 从官网获取
face.appId=LF534BAxwUmaw15fDkGNQNhRM35p3jvxeU17d3vMiom
face.windows.sdkKey=3AfY1jqhfNWcsdDGgc37aqW6ZQPYvCVyoCuRTL3MhYZt
face.libpath=/WIN64
#人脸相似度阈值
face.score=0.75
face.path=/face/
face.path.back=/face/back/
# 上传最大文件限制
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#加解密秘钥
face.secret.key=3a9F7bE2cD5gH1jK8lM4nO6pQ0rS2tU4vW6xY8zA1B3C5D7E9F2G4H6J8K0L2N4P6Q8R0T2V4X6Z8
aes.secret.key=3a9F7bE2cD5gH1jK
user.default.password=1233456
